export enum ProposalStatus {
  INITIALIZED = "INITIALIZED",
  SUBSCRIBER_ADDED = "SUBSCRIBER_ADDED",
  CAR_ADDED = "CAR_ADDED",
  DRIVERS_ADDED = "DRIVERS_ADDED",
  INSURANCE_PLAN_ADDED = "INSURANCE_PLAN_ADDED",
  CONFIRMED = "CONFIRMED",
  PAID = "PAID",
}

export enum ProposalStatusToInt {
  INITIALIZED,
  SUBSCRIBER_ADDED,
  CAR_ADDED,
  DRIVERS_ADDED,
  INSURANCE_PLAN_ADDED,
  CONFIRMED,
  PAID,
}
